### ISSUE TITLE
Errors occurred during my installation on CentOS/ Fedora

### ISSUE THREAD

**Issue by Russyz** [kartverket/where#10]
Sorry to disturb you! There are some problems occurred when I installed where on CentOS/Fedora. Here are issues:
/usr/bin/ld: /home/zhang/Downloads/where/external/iers/src_2010/libiers-dehant/libiers-dehant.a(STEP2DIU.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/zhang/Downloads/where/external/iers/src_2010/libiers-dehant/libiers-dehant.a(STEP2LON.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/zhang/Downloads/where/external/iers/src_2010/libiers-hardisp/libiers-hardisp.a(ADMINT.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/zhang/Downloads/where/external/iers/src_2010/libiers-hardisp/libiers-hardisp.a(TDFRPH.o): relocation R_X86_64_32S against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/zhang/Downloads/where/external/iers/src_2010/libiers-hardisp/libiers-hardisp.a(ETUTC.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
collect2: error: ld returned 1 exit status
error: Command "/usr/bin/gfortran -Wall -g -Wall -g -shared /tmp/tmpib21nlm3/tmp/tmpib21nlm3/src.linux-x86_64-3.9/home/zhang/Downloads/where/external/iers/src_2010/iers_2010module.o /tmp/tmpib21nlm3/tmp/tmpib21nlm3/src.linux-x86_64-3.9/home/zhang/Downloads/where/external/iers/src_2010/fortranobject.o /tmp/tmpib21nlm3/home/zhang/Downloads/where/external/iers/src_2010/APG.o /tmp/tmpib21nlm3/home/zhang/Downloads/where/external/iers/src_2010/ARG2.o /tmp/tmpib21nlm3/home/zhang/Downloads/where/external/iers/src_2010/CNMTX.o /tmp/tmpib21nlm3/home/zhang/Downloads/where/external/iers/src_2010/DEHANTTIDEINEL.o /tmp/tmpib21nlm3/home/zhang/Downloads/where/external/iers/src_2010/FCNNUT.o /tmp/tmpib21nlm3/home/zhang/Downloads/where/external/iers/src_2010/FCUL_A.o /tmp/tmpib21nlm3/home/zhang/Downloads/where/external/iers/src_2010/FCUL_B.o /tmp/tmpib21nlm3/home/zhang/Downloads/where/external/iers/src_2010/FCUL_ZD_HPA.o /tmp/tmpib21nlm3/home/zhang/Downloads/where/external/iers/src_2010/FUNDARG.o /tmp/tmpib21nlm3/home/zhang/Downloads/where/external/iers/src_2010/GCONV2.o /tmp/tmpib21nlm3/home/zhang/Downloads/where/external/iers/src_2010/GMF.o /tmp/tmpib21nlm3/home/zhang/Downloads/where/external/iers/src_2010/GPT2.o /tmp/tmpib21nlm3/home/zhang/Downloads/where/external/iers/src_2010/GPT.o /tmp/tmpib21nlm3/home/zhang/Downloads/where/external/iers/src_2010/HARDISP.o /tmp/tmpib21nlm3/home/zhang/Downloads/where/external/iers/src_2010/HF2002_IERS.o /tmp/tmpib21nlm3/home/zhang/Downloads/where/external/iers/src_2010/ORTHO_EOP.o /tmp/tmpib21nlm3/home/zhang/Downloads/where/external/iers/src_2010/PMSDNUT2.o /tmp/tmpib21nlm3/home/zhang/Downloads/where/external/iers/src_2010/RG_ZONT2.o /tmp/tmpib21nlm3/home/zhang/Downloads/where/external/iers/src_2010/UTLIBR.o /tmp/tmpib21nlm3/home/zhang/Downloads/where/external/iers/src_2010/VMF1.o /tmp/tmpib21nlm3/home/zhang/Downloads/where/external/iers/src_2010/VMF1_HT.o /tmp/tmpib21nlm3/tmp/tmpib21nlm3/src.linux-x86_64-3.9/home/zhang/Downloads/where/external/iers/src_2010/iers_2010-f2pywrappers.o -L/home/zhang/Downloads/where/external/iers/src_2010/libiers-dehant -L/home/zhang/Downloads/where/external/iers/src_2010/libiers-hardisp -L/usr/lib/gcc/x86_64-redhat-linux/11 -L/usr/lib/gcc/x86_64-redhat-linux/11 -L/usr/lib64 -liers-dehant -liers-hardisp -lgfortran -o ./iers_2010.cpython-39-x86_64-linux-gnu.so" failed with exit status 1
make: *** [Makefile:92: /home/zhang/Downloads/where/where/ext/iers_2010.cpython-36m-x86_64-linux-gnu.so] Error 1

**Comment by annsilje** [comment]
Hi,

during `make` the source code of some external libraries will be downloaded and then compiled. This is where the process fails. The external libraries cannot be compiled directly and they need to be patched first. This happens automatically, but will fail if you do not have `patch` installed. One of the problems fixed by the patching is adding the -fPIC option to the makefile of the libraries. Since the error you get complains about this option, my first guess will be that you do not have `patch` installed. Install `patch` (search the package manager for you OS) and try again.

**Comment by Russyz** [comment]
Hello,
Problems solved!
