### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Niu-Liu** [kartverket/where#7]
Hi, 

I just know the where software from the IVS GM2018 proceeding. 
It is really great to have a VLBI analysis software written in python!

I am trying to install where on my MacOS and I got an error.
The error message is listed at the end of this message and the full installation output is attached.
[installation.log](https://github.com/kartverket/where/files/3572416/installation.log)
 
Probably, it is due to the gfortran compiler.
Does where have a special preference of the version of gfortran (or gcc) compiler.
The one I used is of gcc version 8.3.0.

Also, I had a problem of downloading the IERS 2010 software from USNO website.
I think that I was blocked by them because I am in China :-(.
Is there other option for downloading the IERS software, e.g., from the website of Paris Observatory?

Could you please help me with these problems?

Thanks for your time and reply in advance, 
Niu

--------------------ERROR MESSAGE-----------------------
In file included from /var/folders/cx/w871dcfn6h18zc_07dj7mxgm0000gn/T/tmpixsvt77n/src.macosx-10.9-x86_64-3.7/Users/Neo/github/kartverket/where/external/sofa/src/fortranobject.c:2:
In file included from /var/folders/cx/w871dcfn6h18zc_07dj7mxgm0000gn/T/tmpixsvt77n/src.macosx-10.9-x86_64-3.7/Users/Neo/github/kartverket/where/external/sofa/src/fortranobject.h:13:
In file included from /usr/local/miniconda3/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:
In file included from /usr/local/miniconda3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:
In file included from /usr/local/miniconda3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1824:
/usr/local/miniconda3/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "
      "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it with " \
 ^
In file included from /var/folders/cx/w871dcfn6h18zc_07dj7mxgm0000gn/T/tmpixsvt77n/src.macosx-10.9-x86_64-3.7/Users/Neo/github/kartverket/where/external/sofa/src/sofamodule.c:16:
In file included from /var/folders/cx/w871dcfn6h18zc_07dj7mxgm0000gn/T/tmpixsvt77n/src.macosx-10.9-x86_64-3.7/Users/Neo/github/kartverket/where/external/sofa/src/fortranobject.h:13:
In file included from /usr/local/miniconda3/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:
In file included from /usr/local/miniconda3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:
In file included from /usr/local/miniconda3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1824:
/usr/local/miniconda3/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "
      "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it with " \
 ^
/var/folders/cx/w871dcfn6h18zc_07dj7mxgm0000gn/T/tmpixsvt77n/src.macosx-10.9-x86_64-3.7/Users/Neo/github/kartverket/where/external/sofa/src/sofamodule.c:177:12: warning: 
      unused function 'f2py_size' [-Wunused-function]
static int f2py_size(PyArrayObject* var, ...)
           ^
1 warning generated.
2 warnings generated.
dyld: Library not loaded: /usr/local/opt/isl/lib/libisl.19.dylib
  Referenced from: /usr/local/Cellar/gcc/8.3.0_1/libexec/gcc/x86_64-apple-darwin18/8.3.0/f951
  Reason: image not found
gfortran: internal compiler error: Abort trap: 6 signal terminated program f951
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
dyld: Library not loaded: /usr/local/opt/isl/lib/libisl.19.dylib
  Referenced from: /usr/local/Cellar/gcc/8.3.0_1/libexec/gcc/x86_64-apple-darwin18/8.3.0/f951
  Reason: image not found
gfortran: internal compiler error: Abort trap: 6 signal terminated program f951
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
dyld: Library not loaded: /usr/local/opt/isl/lib/libisl.19.dylib
  Referenced from: /usr/local/Cellar/gcc/8.3.0_1/libexec/gcc/x86_64-apple-darwin18/8.3.0/f951
  Reason: image not found
gfortran: internal compiler error: Abort trap: 6 signal terminated program f951
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
dyld: Library not loaded: /usr/local/opt/isl/lib/libisl.19.dylib
  Referenced from: /usr/local/Cellar/gcc/8.3.0_1/libexec/gcc/x86_64-apple-darwin18/8.3.0/f951
  Reason: image not found
gfortran: internal compiler error: Abort trap: 6 signal terminated program f951
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
dyld: Library not loaded: /usr/local/opt/isl/lib/libisl.19.dylib
  Referenced from: /usr/local/Cellar/gcc/8.3.0_1/libexec/gcc/x86_64-apple-darwin18/8.3.0/f951
  Reason: image not found
gfortran: internal compiler error: Abort trap: 6 signal terminated program f951
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
dyld: Library not loaded: /usr/local/opt/isl/lib/libisl.19.dylib
  Referenced from: /usr/local/Cellar/gcc/8.3.0_1/libexec/gcc/x86_64-apple-darwin18/8.3.0/f951
  Reason: image not found
gfortran: internal compiler error: Abort trap: 6 signal terminated program f951
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
dyld: Library not loaded: /usr/local/opt/isl/lib/libisl.19.dylib
  Referenced from: /usr/local/Cellar/gcc/8.3.0_1/libexec/gcc/x86_64-apple-darwin18/8.3.0/f951
  Reason: image not found
gfortran: internal compiler error: Abort trap: 6 signal terminated program f951
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
dyld: Library not loaded: /usr/local/opt/isl/lib/libisl.19.dylib
  Referenced from: /usr/local/Cellar/gcc/8.3.0_1/libexec/gcc/x86_64-apple-darwin18/8.3.0/f951
  Reason: image not found
gfortran: internal compiler error: Abort trap: 6 signal terminated program f951
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
dyld: Library not loaded: /usr/local/opt/isl/lib/libisl.19.dylib
  Referenced from: /usr/local/Cellar/gcc/8.3.0_1/libexec/gcc/x86_64-apple-darwin18/8.3.0/f951
  Reason: image not found
gfortran: internal compiler error: Abort trap: 6 signal terminated program f951
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
dyld: Library not loaded: /usr/local/opt/isl/lib/libisl.19.dylib
  Referenced from: /usr/local/Cellar/gcc/8.3.0_1/libexec/gcc/x86_64-apple-darwin18/8.3.0/f951
  Reason: image not found
gfortran: internal compiler error: Abort trap: 6 signal terminated program f951
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
dyld: Library not loaded: /usr/local/opt/isl/lib/libisl.19.dylib
  Referenced from: /usr/local/Cellar/gcc/8.3.0_1/libexec/gcc/x86_64-apple-darwin18/8.3.0/f951
  Reason: image not found
gfortran: internal compiler error: Abort trap: 6 signal terminated program f951
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
dyld: Library not loaded: /usr/local/opt/isl/lib/libisl.19.dylib
  Referenced from: /usr/local/Cellar/gcc/8.3.0_1/libexec/gcc/x86_64-apple-darwin18/8.3.0/f951
  Reason: image not found
gfortran: internal compiler error: Abort trap: 6 signal terminated program f951
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
dyld: Library not loaded: /usr/local/opt/isl/lib/libisl.19.dylib
  Referenced from: /usr/local/Cellar/gcc/8.3.0_1/libexec/gcc/x86_64-apple-darwin18/8.3.0/f951
  Reason: image not found
gfortran: internal compiler error: Abort trap: 6 signal terminated program f951
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
dyld: Library not loaded: /usr/local/opt/isl/lib/libisl.19.dylib
  Referenced from: /usr/local/Cellar/gcc/8.3.0_1/libexec/gcc/x86_64-apple-darwin18/8.3.0/f951
  Reason: image not found
gfortran: internal compiler error: Abort trap: 6 signal terminated program f951
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
dyld: Library not loaded: /usr/local/opt/isl/lib/libisl.19.dylib
  Referenced from: /usr/local/Cellar/gcc/8.3.0_1/libexec/gcc/x86_64-apple-darwin18/8.3.0/f951
  Reason: image not found
gfortran: internal compiler error: Abort trap: 6 signal terminated program f951
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
dyld: Library not loaded: /usr/local/opt/isl/lib/libisl.19.dylib
  Referenced from: /usr/local/Cellar/gcc/8.3.0_1/libexec/gcc/x86_64-apple-darwin18/8.3.0/f951
  Reason: image not found
gfortran: internal compiler error: Abort trap: 6 signal terminated program f951
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
dyld: Library not loaded: /usr/local/opt/isl/lib/libisl.19.dylib
  Referenced from: /usr/local/Cellar/gcc/8.3.0_1/libexec/gcc/x86_64-apple-darwin18/8.3.0/f951
  Reason: image not found
gfortran: internal compiler error: Abort trap: 6 signal terminated program f951
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
dyld: Library not loaded: /usr/local/opt/isl/lib/libisl.19.dylib
  Referenced from: /usr/local/Cellar/gcc/8.3.0_1/libexec/gcc/x86_64-apple-darwin18/8.3.0/f951
  Reason: image not found
gfortran: internal compiler error: Abort trap: 6 signal terminated program f951
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
dyld: Library not loaded: /usr/local/opt/isl/lib/libisl.19.dylib
  Referenced from: /usr/local/Cellar/gcc/8.3.0_1/libexec/gcc/x86_64-apple-darwin18/8.3.0/f951
  Reason: image not found
gfortran: internal compiler error: Abort trap: 6 signal terminated program f951
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
dyld: Library not loaded: /usr/local/opt/isl/lib/libisl.19.dylib
  Referenced from: /usr/local/Cellar/gcc/8.3.0_1/libexec/gcc/x86_64-apple-darwin18/8.3.0/f951
  Reason: image not found
gfortran: internal compiler error: Abort trap: 6 signal terminated program f951
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
dyld: Library not loaded: /usr/local/opt/isl/lib/libisl.19.dylib
  Referenced from: /usr/local/Cellar/gcc/8.3.0_1/libexec/gcc/x86_64-apple-darwin18/8.3.0/f951
  Reason: image not found
gfortran: internal compiler error: Abort trap: 6 signal terminated program f951
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
dyld: Library not loaded: /usr/local/opt/isl/lib/libisl.19.dylib
  Referenced from: /usr/local/Cellar/gcc/8.3.0_1/libexec/gcc/x86_64-apple-darwin18/8.3.0/f951
  Reason: image not found
gfortran: internal compiler error: Abort trap: 6 signal terminated program f951
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
dyld: Library not loaded: /usr/local/opt/isl/lib/libisl.19.dylib
  Referenced from: /usr/local/Cellar/gcc/8.3.0_1/libexec/gcc/x86_64-apple-darwin18/8.3.0/f951
  Reason: image not found
gfortran: internal compiler error: Abort trap: 6 signal terminated program f951
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
dyld: Library not loaded: /usr/local/opt/isl/lib/libisl.19.dylib
  Referenced from: /usr/local/Cellar/gcc/8.3.0_1/libexec/gcc/x86_64-apple-darwin18/8.3.0/f951
  Reason: image not found
gfortran: internal compiler error: Abort trap: 6 signal terminated program f951
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
dyld: Library not loaded: /usr/local/opt/isl/lib/libisl.19.dylib
  Referenced from: /usr/local/Cellar/gcc/8.3.0_1/libexec/gcc/x86_64-apple-darwin18/8.3.0/f951
  Reason: image not found
gfortran: internal compiler error: Abort trap: 6 signal terminated program f951
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
dyld: Library not loaded: /usr/local/opt/isl/lib/libisl.19.dylib
  Referenced from: /usr/local/Cellar/gcc/8.3.0_1/libexec/gcc/x86_64-apple-darwin18/8.3.0/f951
  Reason: image not found
gfortran: internal compiler error: Abort trap: 6 signal terminated program f951
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
dyld: Library not loaded: /usr/local/opt/isl/lib/libisl.19.dylib
  Referenced from: /usr/local/Cellar/gcc/8.3.0_1/libexec/gcc/x86_64-apple-darwin18/8.3.0/f951
  Reason: image not found
gfortran: internal compiler error: Abort trap: 6 signal terminated program f951
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
dyld: Library not loaded: /usr/local/opt/isl/lib/libisl.19.dylib
  Referenced from: /usr/local/Cellar/gcc/8.3.0_1/libexec/gcc/x86_64-apple-darwin18/8.3.0/f951
  Reason: image not found
gfortran: internal compiler error: Abort trap: 6 signal terminated program f951
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
dyld: Library not loaded: /usr/local/opt/isl/lib/libisl.19.dylib
  Referenced from: /usr/local/Cellar/gcc/8.3.0_1/libexec/gcc/x86_64-apple-darwin18/8.3.0/f951
  Reason: image not found
gfortran: internal compiler error: Abort trap: 6 signal terminated program f951
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
dyld: Library not loaded: /usr/local/opt/isl/lib/libisl.19.dylib
  Referenced from: /usr/local/Cellar/gcc/8.3.0_1/libexec/gcc/x86_64-apple-darwin18/8.3.0/f951
  Reason: image not found
gfortran: internal compiler error: Abort trap: 6 signal terminated program f951
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
dyld: Library not loaded: /usr/local/opt/isl/lib/libisl.19.dylib
  Referenced from: /usr/local/Cellar/gcc/8.3.0_1/libexec/gcc/x86_64-apple-darwin18/8.3.0/f951
  Reason: image not found
gfortran: internal compiler error: Abort trap: 6 signal terminated program f951
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
error: Command "/usr/local/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -m64 -fPIC -O3 -funroll-loops -I/var/folders/cx/w871dcfn6h18zc_07dj7mxgm0000gn/T/tmpixsvt77n/src.macosx-10.9-x86_64-3.7/Users/Neo/github/kartverket/where/external/sofa/src -I/usr/local/miniconda3/lib/python3.7/site-packages/numpy/core/include -I/usr/local/miniconda3/include/python3.7m -c -c /Users/Neo/github/kartverket/where/external/sofa/src/apcg13.for -o /var/folders/cx/w871dcfn6h18zc_07dj7mxgm0000gn/T/tmpixsvt77n/Users/Neo/github/kartverket/where/external/sofa/src/apcg13.o" failed with exit status 4
make: *** [/Users/Neo/github/kartverket/where/where/ext/sofa.cpython-36m-x86_64-linux-gnu.so] Error 1

**Comment by annsilje** [comment]
I have never used MacOS myself, so I cannot give you specific answers, but I can try to give you some advice. 

Regarding the IERS 2010 source code itself:
If you look at the file https://github.com/kartverket/where/blob/master/config/download_iers_2010.conf, it describes where the source codes files are downloaded from and which directories to store the files in. If you find another URL to download these files from you can try to edit your local version of this file. If you obtain the source code files by some other means you can store the files in the directories described by that file and the download step will be skipped when you try to make Where. Maybe you could try to ask the IERS (for instance through http://iers-conventions.obspm.fr/contact.php) for an URL you can access or for the source code directly. 

Regarding the compilation:
I would recommend trying to compile the source code by itself and not through the Where makefile. Once you solve the problems with compiling the source code you can go back and use the Where makefile. Each external library comes with its own makefile (which is used by Where). Have you tried solutions like this: https://github.com/Homebrew/homebrew-core/issues/25293 to solve the compiler issue? Personally I am using GNU Fortran (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609 for compiling. I am not aware of any requirement for using a specific compiler version.

**Comment by Niu-Liu** [comment]
Thanks very much! 

I reinstalled my gcc compiler and it did work! 

As for the IERS code, I modified the source_url parameter from "ftp://maia.usno.navy.mil/conventions/content/" to "http://iers-conventions.obspm.fr/content/". (For whom may encounter the same problem as I)

But now, I have new problems when I try to analyze single session, following the example you give. 
The links to download "IVS_SrcNamesTable.txt" and "mean_pole_2015.txt" seems invalid, latter being "# TODO github/mean_pole_2015.txt".

By the way, I would like to read and understand (if possible) your code, but I don't know where to begin. Would you please have any suggestions?

Cheers,
Niu

**Comment by annsilje** [comment]
Thanks you for pointing out these mistakes. I had forgotten to update the URLs. I have updated the files config/files.conf and config/files_pipeline_vlbi.conf in the repository so you should be able to just download the new versions. The changes are:

- "IVS-SrcNamesTable.txt to be downloaded from ftp://cddis.gsfc.nasa.gov/vlbi/gsfc/ancillary/solve_apriori/
- "mean_pole_2015.txt" to be downloaded from https://raw.githubusercontent.com/kartverket/where/master/download
- The URLs for the troposphere products from TUWien is also updated since they changed server. 

To understand the code I would recommend starting with the file pipelines/vlbi.py. We think of an analysis as a processing pipeline that consist of several stages. The stages are defined in this file and you can follow the imports and function calls to see what each stage does. The stages defined for VLBI is "read", "edit", "calculate", "estimate", "write". Looking at the configuration files config/where.conf and config/where_pipeline_vlbi.conf can also be useful.

**Comment by Niu-Liu** [comment]
Thanks a lot! :-) I will follow your suggestions
