### ISSUE TITLE
AttributeError: module 'where.data' has no attribute 'dataset3'

### ISSUE THREAD

**Issue by Russyz** [kartverket/where#9]
Good afternoon,

I have successfully installed the program ( v1.1.1) on my PC (Linux), but i find errors in `where.data.position_table`. 
Also, in `where.models.site.solid_ptides_test.py`

**Comment by annsilje** [comment]
Hi,

I am not sure I understand your problem. There is no file or module named exactly` where.data.positition_table` or `where.models.site.solid_ptides_test`. in v1.1.1.  Which command did you use to run to the program? Can you run it again and add the option `-T` and post the output. Did you also manage to update the dependencies? This should happen if you run `make ` after downloading the new source code.

**Comment by Russyz** [comment]
Hello, I'm glad to get your reply.There are two main issues so that I need your help.
1.
I run&nbsp;test_position_table.py file, then get errors below.
~/where/where/data/tests$&nbsp;python test_position_table.py&nbsp;
EEE
======================================================================
ERROR: test_convert_enu_to_itrs (__main__.TestPositionTable)
----------------------------------------------------------------------
Traceback (most recent call last):
&nbsp; File "test_position_table.py", line 38, in setUp
&nbsp; &nbsp; self.dset = data.dataset3.Dataset(rundate, tech=None, stage=None, dataset_name="test_where", dataset_id=0, empty=True)
AttributeError: module 'where.data' has no attribute 'dataset3'


======================================================================
ERROR: test_convert_itrs_to_enu (__main__.TestPositionTable)
----------------------------------------------------------------------
Traceback (most recent call last):
&nbsp; File "test_position_table.py", line 38, in setUp
&nbsp; &nbsp; self.dset = data.dataset3.Dataset(rundate, tech=None, stage=None, dataset_name="test_where", dataset_id=0, empty=True)
AttributeError: module 'where.data' has no attribute 'dataset3'


======================================================================
ERROR: test_llh (__main__.TestPositionTable)
----------------------------------------------------------------------
Traceback (most recent call last):
&nbsp; File "test_position_table.py", line 38, in setUp
&nbsp; &nbsp; self.dset = data.dataset3.Dataset(rundate, tech=None, stage=None, dataset_name="test_where", dataset_id=0, empty=True)
AttributeError: module 'where.data' has no attribute 'dataset3'


----------------------------------------------------------------------
Ran 3 tests in 0.000s


FAILED (errors=3)



2.
Another problem is about a test file for&nbsp;solid_ptides.py named&nbsp;solid_ptides_test.py.&nbsp;


&nbsp; File "/home/z8/下载/download/where-master/where/models/site/solid_ptides_test.py", line 79, in <module&gt;
&nbsp; &nbsp; solid_pole_tides_station(2019,8,np.arange(1,10),0,0,0)
&nbsp; File "/home/z8/下载/download/where-master/where/models/site/solid_ptides_test.py", line 57, in solid_pole_tides_station
&nbsp; &nbsp; eop = apriori.get("eop", time=time)
&nbsp; File "/home/z8/下载/download/where-master/where/apriori/__init__.py", line 70, in get
&nbsp; &nbsp; return plugins.call(package_name=__name__, plugin_name=datasource_name, **kwargs)
&nbsp; File "/home/z8/anaconda3/lib/python3.7/site-packages/midgard/dev/plugins.py", line 248, in call
&nbsp; &nbsp; return plugin.function(**plugin_args)
&nbsp; File "/home/z8/下载/download/where-master/where/apriori/eop.py", line 103, in get_eop
&nbsp; &nbsp; return Eop(_EOP_DATA, time, models=models, pole_model=pole_model, window=window)
&nbsp; File "/home/z8/下载/download/where-master/where/apriori/eop.py", line 154, in __init__
&nbsp; &nbsp; self.mean_pole_last_idx = len(data["year"]) - 1



ALSO, I don't know how to establish a dset in file like solid_tides.py&nbsp;. I'm a rookie. So it's difficult for me. I just want to correct the tide impact for a laser ranging station.
THANK YOU!
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kartverket/where"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月25日(星期四) 下午3:51
收件人:&nbsp;"kartverket/where"<where@noreply.github.com&gt;;
抄送:&nbsp;"张才士"<397368245@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kartverket/where] AttributeError: module 'where.data' has no attribute 'dataset3' (#9)





 
Hi,
 
I am not sure I understand your problem. There is no file or module named exactly where.data.positition_table or where.models.site.solid_ptides_test. in v1.1.1.  Which command did you use to run to the program? Can you run it again and add the option -T and post the output. Did you also manage to update the dependencies? This should happen if you run make  after downloading the new source code.

**Comment by annsilje** [comment]
Hello again,

Have you made changes to the code in `test_position_table.py`? Line 38, which the error message complains about, looks different from the code in v1.1.1.

The test cases in `where.data.test` is written to test a previous version of the module `dataset`. This version no longer exists and have been replaced with a module named `dataset3`. The test cases are not compatible with `dataset3 `and should be updated, but sadly this has not been a priority. Sorry for the confusion this causes. So you should not try to make this test run because it requires a major rewrite.

Is `solid_ptides_test.py` a file you have created? I cannot find any file with that name in the repository.

If I understand you correctly you want to use the functions in `solid_ptides.py` to correct for this effect for a laser ranging station and you are trying to construct the required input argument `dset`.  This is not something that will work out of the box, but it will require some work and setup. I can give you some hints for where you can look at similar code. The variable `dset` have been created and filled with data during the previous stages in the program. It is first constructed in the `read` stage. Look in `where.pipelines.vlbi.py` or `where.pipeline.slr.py` and follow the imports and functions used. After `read `the next stage is `edit`, which may do changes to the data in the `dataset `created by read. After that the next stage is `calculate `which is where functions like `solid_ptides` is called.

**Comment by Russyz** [comment]
I've changed nothing in&nbsp;test_position_table.py. I just want to make sure that if I have installed your code well. So it doesn't matter.


YES. I created a&nbsp;file named&nbsp;solid_ptides_test.py. Also, I want&nbsp;to calculate the impacts on other kinds of tides in where.models. I'll learn&nbsp;how to&nbsp;construct&nbsp;the required input argument&nbsp;dset from your advices. Thank you!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kartverket/where"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月25日(星期四) 晚上6:01
收件人:&nbsp;"kartverket/where"<where@noreply.github.com&gt;;
抄送:&nbsp;"张才士"<397368245@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kartverket/where] AttributeError: module 'where.data' has no attribute 'dataset3' (#9)





 
Hello again,
 
Have you made changes to the code in test_position_table.py? Line 38, which the error message complains about, looks different from the code in v1.1.1.
 
The test cases in where.data.test is written to test a previous version of the module dataset. This version no longer exists and have been replaced with a module named dataset3. The test cases are not compatible with dataset3 and should be updated, but sadly this has not been a priority. Sorry for the confusion this causes. So you should not try to make this test run because it requires a major rewrite.
 
Is solid_ptides_test.py a file you have created? I cannot find any file with that name in the repository.
 
If I understand you correctly you want to use the functions in solid_ptides.py to correct for this effect for a laser ranging station and you are trying to construct the required input argument dset.  This is not something that will work out of the box, but it will require some work and setup. I can give you some hints for where you can look at similar code. The variable dset have been created and filled with data during the previous stages in the program. It is first constructed in the read stage. Look in where.pipelines.vlbi.py or where.pipeline.slr.py and follow the imports and functions used. After read the next stage is edit, which may do changes to the data in the dataset created by read. After that the next stage is calculate which is where functions like solid_ptides is called.
